### ISSUE TITLE
module not found 'redux'

### ISSUE THREAD

**Issue by jspeis** [jazzido/mondrian-rest-ui#2]
checking out from scratch and following the instructions I got the error:

```
Failed to compile.

Error in ./src/index.js
Module not found: 'redux' in /Users/jspeiser/code/mondrian-rest-ui/src
```

Doing an ```npm install redux``` fixes the problem. I notice that redux is listed as a ```peerDependency``` in package.json, so not sure if I messed something up locally or if redux needs to be listed as a  regular dependency?

**Comment by jazzido** [comment]
Hrm…I'm not sure why I added `redux` to `peerDependencies`. It's probably fine to move it to `dependencies`.
