### ISSUE TITLE
use environment variable for cube path

### ISSUE THREAD

**Issue by jspeis** [jazzido/mondrian-rest-ui#6]

**Comment by jazzido** [comment]
The thing is that `mondrian-rest-ui` is a client only app, so making it use an envvar for that would force us to run it under Express or similar.

What about a global variable that can be defined in a `<script>` tag in `index.html`?

**Comment by jspeis** [comment]
would it be possible to pull an optional environment variable at build time and use that way?

**Comment by jazzido** [comment]
Absolutely, here's how: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables

PRs welcome :)

**Comment by jazzido** [comment]
As mentioned in Slack:

In `settings.js`, you can set a global variable to the URL of the `mondrian-rest` server like so: `export const client = new Client(window.__API_ENDPOINT__)`

If you don't want to change `index.html`, here's an nginx trick to set that variable:

```
 location /ui {
        sub_filter '<head>' '<head><script>window.__API_ENDPOINT__ = "http://url.of.mondrian.server";</script>';
        sub_filter_once on;
        alias /home/hermes/mondrian-rest-ui/build;
    }
```
