### ISSUE TITLE
[Feature] search list of cube names

### ISSUE THREAD

**Issue by jspeis** [jazzido/mondrian-rest-ui#7]
would could be quick and easy with react-select

**Comment by jazzido** [comment]
It was indeed quick and easy: https://github.com/jazzido/mondrian-rest-ui/tree/cube-select

Can you give it a try? I'll merge to master after you test it.

**Comment by jazzido** [comment]
Closed in 9bb1e991198b7c0b6a3ab18ebaad5f140753c315
